server:
  port: 30015

spring:
  application:
    name: sn-article-displacement
  cloud:
    nacos:
      discovery:
        server-addr: http://192.168.1.214:8848
        namespace: gx-police-test
        ip: 192.168.1.15
        port: 30015
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.29.128:3306/ba?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
#    username: root
#    password: user*2023
#    type: com.zaxxer.hikari.HikariDataSource
#    hikari:
#      maximum-pool-size: 120
#      connection-timeout: 30000
#      minimum-idle: 10
#      idle-timeout: 500000
#      max-lifetime: 540000
#  jpa:
#    hibernate:
#      ddl-auto: update

  redis:
    database: 1
    host: 192.168.1.214
    port: 6379
    password:
    timeout: 6000ms
    jedis:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 10
        min-idle: 5
  datasource:
    driver-class-name: dm.jdbc.driver.DmDriver
    url: jdbc:dm://192.168.1.214:30236/BA?zeroDateTimeBehavior=convertToNull&userUnicode=true&characterEncoding=UTF-8
    username: SYSDBA
    password: SYSDBA001
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 120
      connection-timeout: 30000
      minimum-idle: 10
      idle-timeout: 500000
      max-lifetime: 540000

  jpa:
    database-platform: org.hibernate.dialect.DmDialect
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.DmDialect
        default_schema: BA
        hbm2ddl:
          auto: update
        show_sql: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

mqtt:
  hostUrl: tcp://192.168.29.128:1883
  username: admin
  password: public
  inboundClientIdBA: displacement-inbound-BA
  inboundGatewayTopicBA: /GATEWAY/BA2/GXGAT/#
  inboundClientIdNY: displacement-inbound-NY
  inboundGatewayTopicNY: /GATEWAY/NY/GXGAT/#
  inboundClientIdDL: displacement-inbound-DL
  inboundGatewayTopicDL: /GATEWAY/DL/GXGAT/#
  inboundClientIdHJ: displacement-inbound-HJ
  inboundGatewayTopicHJ: /GATEWAY/HJ/GXGAT/#
  inboundClientIdIAQ: displacement-inbound-IAQ
  inboundGatewayTopicIAQ: /GATEWAY/IAQ/GXGAT/#

  outboundClientId: displacement-outbound
  outboundPlatformTopics:
    - /GATEWAY/NBMTWPYW/#
  defaultTopic: /GATEWAY/NBMTWPYW/#
  timeout: 1000
  keepalive: 60
  enabled: false

ba:
  topic: /GATEWAY/BA2/GXGAT/command
  linkageTaskTime: 5